// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as connectivity$0 from "../connectivity/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as content$0 from "../content/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as protocol$0 from "../protocol/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as transfer$0 from "../transfer/models.js";

export interface ContentActionResult {
    "task_id": string;
    "action": string;
    "state": string;
}

export interface ContentCleanupResult {
    "removed": number;
    "protected": number;
}

export interface ContentDraft {
    "id": string;
    "snapshot": content$0.Snapshot;
    "revision": number;
    "state": string;
    "created_at": string;
}

export interface ContentSettings {
    "retain_sent_snapshots": boolean;
}

export interface ContentTaskInfo {
    "task_id": string;
    "kind": content$0.Kind;
    "size": number;
    "width"?: number;
    "height"?: number;
    "mode": string;
    "available": boolean;
    "can_preview": boolean;
    "can_copy": boolean;
    "can_open": boolean;
    "can_save": boolean;
}

export interface ContentTextRequest {
    "request_id": string;
    "kind": content$0.Kind;
    "text": string;
}

export interface DeviceInfo {
    "id": string;
    "group_id": string;
    "name": string;
    "public_key_hex": string;
    "admin": boolean;
    "online": boolean;
    "trusted": boolean;
    "always_accept": boolean;
    "nearby": boolean;
    "blocked": boolean;
    "profile": DeviceProfile;
}

/**
 * DeviceProfile contains local presentation and destination preferences only.
 * Key pins, local denial, and auto-accept remain owned by the identity layer.
 */
export interface DeviceProfile {
    "peer_id": string;
    "alias": string;
    "my_device": boolean;
    "pinned": boolean;
    "position": number;
    "receive_directory": string;
    "last_used_at": string;
    "revision": number;
}

/**
 * DiagnosticIdentity intentionally omits local filesystem locations. Identity()
 * is an explicit local profile view; diagnostics are safe to export by default.
 */
export interface DiagnosticIdentity {
    "id": string;
    "public_key_hex": string;
}

export interface Diagnostics {
    "history_persisted": boolean;
    "restart_recovery_supported": boolean;
    "byte_resume_supported": boolean;
    "history_error"?: string;
    "version": string;
    "platform": string;
    "relay": boolean;
    "identity": DiagnosticIdentity;
    "server_url"?: string;
    "server_health": string;
    "capabilities": protocol$0.Capabilities;
    "trusted_peers": number;
    "generated_at": string;
    "health_failure"?: string;
}

export interface DirectTimings {
    "peer_lookup_ms": number;
    "signaling_connect_ms": number;
    "endpoint_setup_ms": number;
    "peer_response_ms": number;
    "ice_ms": number;
    "quic_handshake_ms": number;
    "total_connect_ms": number;
}

export interface DraftPreview {
    "revision": number;
    "files": number;
    "directories": number;
    "bytes": number;
    "complete": boolean;
    "problem"?: string;
}

export interface EnqueueContentRequest {
    "request_id": string;
    "draft_id": string;
    "draft_revision": number;
    "peer_id": string;
    "allow_file_fallback": boolean;
    "wait_for_peer": boolean;
    "expires_at": string;
}

export interface EnqueueRequest {
    "request_id": string;
    "peer_id": string;
    "paths": string[] | null;
    "wait_for_peer": boolean;
    "expires_at": string;
}

export interface IdentityInfo {
    "id": string;
    "public_key_hex": string;
    "data_dir": string;
}

export interface InboxCleanupIssue {
    "task_id": string;
    "code": string;
}

export interface InboxCleanupResult {
    "removed": string[] | null;
    "protected": string[] | null;
    "issues": InboxCleanupIssue[] | null;
}

export interface InboxFile {
    "file_id": number;
    "name": string;
    "kind": string;
    "size": number;
    "selected": boolean;
}

export interface InboxFilesPage {
    "files": InboxFile[] | null;
    "next_cursor": string;
    "available": boolean;
}

/**
 * InboxItem is a reduced historical view, never a recovery record or an export
 * of absolute filesystem locations and private connection diagnostics.
 */
export interface InboxItem {
    "task_id": string;
    "peer_id": string;
    "direction": string;
    "state": string;
    "summary": string;
    "file_count": number;
    "verified_bytes": number;
    "committed_bytes": number;
    "bilateral_confirmed": boolean;
    "started_at": string;
    "ended_at": string;
    "revision": number;
    "can_resend": boolean;
    "can_resume": boolean;
    "can_forget": boolean;
}

export interface InboxPage {
    "items": InboxItem[] | null;
    "next_cursor": string;
}

export interface InboxQuery {
    "peer_id": string;
    "direction": string;
    "states": string[] | null;
    "after": string;
    "before": string;
    "search": string;
    "cursor": string;
    "limit": number;
}

export interface InboxRecordRef {
    "task_id": string;
    "revision": number;
}

/**
 * InboxStatus describes the persistent receiver without creating a visible
 * transfer task merely because the application is idle.
 */
export interface InboxStatus {
    "enabled": boolean;
    "signaling_connected": boolean;
    "listening": boolean;
    "directory"?: string;
    "connected_at"?: string;
    "connection_count": number;
    "last_error"?: string;
    "lan_available": boolean;
    "lan_peer_count": number;
    "lan_last_error"?: string;
}

export interface IncomingFile {
    "id": number;
    "path": string;
    "type": string;
    "size": number;
    "selected": boolean;
    "target_path"?: string;
}

export interface IncomingFilesPage {
    "content"?: transfer$0.ContentDescriptor | null;
    "file_fallback"?: boolean;
    "revision": number;
    "files": IncomingFile[] | null;
    "offset": number;
    "total_entries": number;
    "original_total": number;
    "directory": string;
    "subset_supported": boolean;
    "resume": boolean;
}

export interface IncomingFilesRequest {
    "expected_revision": number;
    "offset": number;
    "limit": number;
}

export interface IncomingPlanPreview {
    "revision": number;
    "plan_digest": string;
    "directory": string;
    "summary": transfer$0.PlanSummary;
    "available_bytes": number;
    "reserved_bytes": number;
    "required_bytes": number;
    "space_sufficient": boolean;
    "space_estimate": string;
}

export interface IncomingPlanRequest {
    "expected_revision": number;
    "directory": string;
    "selected_ids": number[] | null;
    "conflict_policy": transfer$0.ConflictPolicy;
    "policies": { [_ in `${number}`]?: transfer$0.ConflictPolicy } | null;
}

export interface InvitationInfo {
    "token": string;
    "expires_at": string;
    "expires_in_seconds": number;
}

export interface MembershipStatus {
    /**
     * pending, member, not_member, auth_failed, unavailable
     */
    "state": string;

    /**
     * unknown, member, admin
     */
    "role": string;
    "message"?: string;
}

export interface QueueItem {
    "id": string;
    "request_id": string;
    "peer_id": string;
    "source_summary": string;
    "state": string;
    "position": number;
    "task_id": string;
    "expires_at": string;
    "revision": number;
    "created_at": string;
    "updated_at": string;
    "last_error": string;
    "wait_for_peer": boolean;
    "content"?: content$0.Snapshot | null;
}

export interface ResendInboxRequest {
    "task_id": string;
    "request_id": string;
    "wait_for_peer": boolean;
}

/**
 * SendDraft is local metadata. Paths are never used as file-content IPC, and
 * persisting a draft does not authorise a send or open any of its file bodies.
 */
export interface SendDraft {
    "id": string;
    "paths": string[] | null;
    "peer_id": string;
    "revision": number;
    "updated_at": string;
}

/**
 * TaskSnapshot is the process-lifetime application view used by Wails and CLI.
 * It intentionally contains metadata only; file bytes never cross this boundary.
 */
export interface TaskPhaseEvent {
    "phase": string;
    "at": string;
}

export interface TaskSnapshot {
    /**
     * compatibility alias for task_id
     */
    "id": string;
    "task_id": string;
    "attempt_id": string;
    "direction": string;
    "peer_id"?: string;
    "source_summary"?: string;
    "manifest_summary"?: string;
    "original_total": number;
    "selected_files": number;
    "selected_entries": number;
    "skipped_files": number;
    "skipped_entries": number;
    "skipped_bytes": number;
    "receive_plan_digest"?: string;
    "selection_digest"?: string;
    "file_count"?: number;
    "target_directory"?: string;
    "state": string;
    "phase": string;
    "processed_bytes": number;
    "total_bytes"?: number | null;
    "rate_bytes_per_second"?: number | null;
    "started_at": string;
    "updated_at": string;
    "ended_at"?: string;
    "error_code"?: string;
    "error_message"?: string;
    "transfer_id"?: string;
    "session_id"?: string;
    "ice_generation"?: number;
    "manifest_digest"?: string;
    "chunk_size"?: number;
    "sent_bytes": number;
    "received_bytes": number;
    "retransmitted_bytes": number;
    "verified_bytes": number;
    "committed_bytes": number;
    "committed_files": number;
    "bilateral_confirmed": boolean;
    "connection_method"?: string;
    "transport_protocol"?: string;
    "relay": boolean;
    "base_socket"?: string;
    "network_interface"?: string;
    "address_family"?: string;
    "local_candidate"?: string;
    "remote_candidate"?: string;
    "local_candidate_type"?: string;
    "remote_candidate_type"?: string;
    "stun_requests_sent": number;
    "stun_responses_received": number;
    "signaling_bytes_sent": number;
    "signaling_bytes_received": number;
    "ice_state_timeline"?: connectivity$0.ICEStateEvent[] | null;
    "phase_timeline"?: TaskPhaseEvent[] | null;
    "tls_version"?: number;
    "alpn"?: string;
    "connect_timings": DirectTimings;
    "can_cancel": boolean;
    "can_retry": boolean;
    "can_pause": boolean;
    "can_resume": boolean;
    "revision": number;
    "history_persisted": boolean;
    "restart_recovery_supported": boolean;
    "byte_resume_supported": boolean;
}

export interface WorkspaceChange {
    "epoch": string;
    "revision": number;
}

/**
 * WorkspaceSnapshot contains local presentation metadata only. Private source
 * recovery maps, checkpoint paths and file/image bytes never cross this DTO.
 */
export interface WorkspaceSnapshot {
    "epoch": string;
    "revision": number;
    "draft": SendDraft;
    "queue": QueueItem[] | null;
    "tasks": TaskSnapshot[] | null;
    "queue_paused": boolean;
    "persistence_available": boolean;
}
