// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as protocol$0 from "../protocol/models.js";

export interface DeviceInfo {
    "id": string;
    "group_id": string;
    "name": string;
    "public_key_hex": string;
    "admin": boolean;
    "online": boolean;
    "trusted": boolean;
}

/**
 * DiagnosticIdentity intentionally omits local filesystem locations. Identity()
 * is an explicit local profile view; diagnostics are safe to export by default.
 */
export interface DiagnosticIdentity {
    "id": string;
    "public_key_hex": string;
}

export interface Diagnostics {
    "history_persisted": boolean;
    "restart_recovery_supported": boolean;
    "byte_resume_supported": boolean;
    "history_error"?: string;
    "version": string;
    "platform": string;
    "relay": boolean;
    "identity": DiagnosticIdentity;
    "server_url"?: string;
    "server_health": string;
    "capabilities": protocol$0.Capabilities;
    "trusted_peers": number;
    "generated_at": string;
    "health_failure"?: string;
}

export interface IdentityInfo {
    "id": string;
    "public_key_hex": string;
    "data_dir": string;
}

export interface InvitationInfo {
    "token": string;
    "expires_at": string;
}

export interface MembershipStatus {
    /**
     * pending, member, not_member, auth_failed, unavailable
     */
    "state": string;

    /**
     * unknown, member, admin
     */
    "role": string;
    "message"?: string;
}

/**
 * TaskSnapshot is the process-lifetime application view used by Wails and CLI.
 * It intentionally contains metadata only; file bytes never cross this boundary.
 */
export interface TaskSnapshot {
    "id": string;
    "direction": string;
    "peer_id"?: string;
    "source_summary"?: string;
    "manifest_summary"?: string;
    "file_count"?: number;
    "target_directory"?: string;
    "state": string;
    "phase": string;
    "processed_bytes": number;
    "total_bytes"?: number | null;
    "rate_bytes_per_second"?: number | null;
    "started_at": string;
    "updated_at": string;
    "ended_at"?: string;
    "error_code"?: string;
    "error_message"?: string;
    "transfer_id"?: string;
    "session_id"?: string;
    "connection_method"?: string;
    "transport_protocol"?: string;
    "relay": boolean;
    "can_cancel": boolean;
    "can_retry": boolean;
    "can_pause": boolean;
    "can_resume": boolean;
    "revision": number;
    "history_persisted": boolean;
    "restart_recovery_supported": boolean;
    "byte_resume_supported": boolean;
}
