// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as connectivity$0 from "../connectivity/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as protocol$0 from "../protocol/models.js";

export interface DeviceInfo {
    "id": string;
    "group_id": string;
    "name": string;
    "public_key_hex": string;
    "admin": boolean;
    "online": boolean;
    "trusted": boolean;
    "always_accept": boolean;
    "nearby": boolean;
}

/**
 * DiagnosticIdentity intentionally omits local filesystem locations. Identity()
 * is an explicit local profile view; diagnostics are safe to export by default.
 */
export interface DiagnosticIdentity {
    "id": string;
    "public_key_hex": string;
}

export interface Diagnostics {
    "history_persisted": boolean;
    "restart_recovery_supported": boolean;
    "byte_resume_supported": boolean;
    "history_error"?: string;
    "version": string;
    "platform": string;
    "relay": boolean;
    "identity": DiagnosticIdentity;
    "server_url"?: string;
    "server_health": string;
    "capabilities": protocol$0.Capabilities;
    "trusted_peers": number;
    "generated_at": string;
    "health_failure"?: string;
}

export interface DirectTimings {
    "peer_lookup_ms": number;
    "signaling_connect_ms": number;
    "endpoint_setup_ms": number;
    "peer_response_ms": number;
    "ice_ms": number;
    "quic_handshake_ms": number;
    "total_connect_ms": number;
}

export interface IdentityInfo {
    "id": string;
    "public_key_hex": string;
    "data_dir": string;
}

/**
 * InboxStatus describes the persistent receiver without creating a visible
 * transfer task merely because the application is idle.
 */
export interface InboxStatus {
    "enabled": boolean;
    "signaling_connected": boolean;
    "listening": boolean;
    "directory"?: string;
    "connected_at"?: string;
    "connection_count": number;
    "last_error"?: string;
    "lan_available": boolean;
    "lan_peer_count": number;
    "lan_last_error"?: string;
}

export interface InvitationInfo {
    "token": string;
    "expires_at": string;
    "expires_in_seconds": number;
}

export interface MembershipStatus {
    /**
     * pending, member, not_member, auth_failed, unavailable
     */
    "state": string;

    /**
     * unknown, member, admin
     */
    "role": string;
    "message"?: string;
}

/**
 * TaskSnapshot is the process-lifetime application view used by Wails and CLI.
 * It intentionally contains metadata only; file bytes never cross this boundary.
 */
export interface TaskPhaseEvent {
    "phase": string;
    "at": string;
}

export interface TaskSnapshot {
    /**
     * compatibility alias for task_id
     */
    "id": string;
    "task_id": string;
    "attempt_id": string;
    "direction": string;
    "peer_id"?: string;
    "source_summary"?: string;
    "manifest_summary"?: string;
    "file_count"?: number;
    "target_directory"?: string;
    "state": string;
    "phase": string;
    "processed_bytes": number;
    "total_bytes"?: number | null;
    "rate_bytes_per_second"?: number | null;
    "started_at": string;
    "updated_at": string;
    "ended_at"?: string;
    "error_code"?: string;
    "error_message"?: string;
    "transfer_id"?: string;
    "session_id"?: string;
    "ice_generation"?: number;
    "manifest_digest"?: string;
    "chunk_size"?: number;
    "sent_bytes": number;
    "received_bytes": number;
    "retransmitted_bytes": number;
    "verified_bytes": number;
    "committed_bytes": number;
    "committed_files": number;
    "bilateral_confirmed": boolean;
    "connection_method"?: string;
    "transport_protocol"?: string;
    "relay": boolean;
    "base_socket"?: string;
    "network_interface"?: string;
    "address_family"?: string;
    "local_candidate"?: string;
    "remote_candidate"?: string;
    "local_candidate_type"?: string;
    "remote_candidate_type"?: string;
    "stun_requests_sent": number;
    "stun_responses_received": number;
    "signaling_bytes_sent": number;
    "signaling_bytes_received": number;
    "ice_state_timeline"?: connectivity$0.ICEStateEvent[] | null;
    "phase_timeline"?: TaskPhaseEvent[] | null;
    "tls_version"?: number;
    "alpn"?: string;
    "connect_timings": DirectTimings;
    "can_cancel": boolean;
    "can_retry": boolean;
    "can_pause": boolean;
    "can_resume": boolean;
    "revision": number;
    "history_persisted": boolean;
    "restart_recovery_supported": boolean;
    "byte_resume_supported": boolean;
}
