// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Change {
    "sequence": number;
    "text": boolean;
    "link": boolean;
    "image": boolean;
}
