// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateInvitation() {
  return window['go']['main']['App']['CreateInvitation']();
}

export function Devices() {
  return window['go']['main']['App']['Devices']();
}

export function Diagnostics() {
  return window['go']['main']['App']['Diagnostics']();
}

export function Identity() {
  return window['go']['main']['App']['Identity']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
