// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {main} from '../models';

export function CreateInvitation():Promise<app.InvitationInfo>;

export function Devices():Promise<Array<app.DeviceInfo>>;

export function Diagnostics():Promise<app.Diagnostics>;

export function Identity():Promise<app.IdentityInfo>;

export function Status():Promise<main.DesktopStatus>;
