// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptTask(arg1) {
  return window['go']['main']['App']['AcceptTask'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function CreateInvitation() {
  return window['go']['main']['App']['CreateInvitation']();
}

export function Devices() {
  return window['go']['main']['App']['Devices']();
}

export function Diagnostics() {
  return window['go']['main']['App']['Diagnostics']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function Identity() {
  return window['go']['main']['App']['Identity']();
}

export function JoinGroup(arg1, arg2) {
  return window['go']['main']['App']['JoinGroup'](arg1, arg2);
}

export function NetworkInterfaces() {
  return window['go']['main']['App']['NetworkInterfaces']();
}

export function OpenTaskDirectory(arg1) {
  return window['go']['main']['App']['OpenTaskDirectory'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function PickSourceDirectory() {
  return window['go']['main']['App']['PickSourceDirectory']();
}

export function Preferences() {
  return window['go']['main']['App']['Preferences']();
}

export function RejectTask(arg1) {
  return window['go']['main']['App']['RejectTask'](arg1);
}

export function RetryTask(arg1) {
  return window['go']['main']['App']['RetryTask'](arg1);
}

export function SavePreferences(arg1) {
  return window['go']['main']['App']['SavePreferences'](arg1);
}

export function StartReceive(arg1, arg2) {
  return window['go']['main']['App']['StartReceive'](arg1, arg2);
}

export function StartSend(arg1, arg2) {
  return window['go']['main']['App']['StartSend'](arg1, arg2);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Tasks() {
  return window['go']['main']['App']['Tasks']();
}

export function TrustDevice(arg1, arg2) {
  return window['go']['main']['App']['TrustDevice'](arg1, arg2);
}
