#import <Cocoa/Cocoa.h>
#import <ImageIO/ImageIO.h>
#include <stdlib.h>
#include <string.h>

static const size_t LinkSendMaxImageBytes = 32 * 1024 * 1024;
static const uint64_t LinkSendMaxImagePixels = 40000000;
static const uint64_t LinkSendMaxImageDimension = 32768;

typedef struct {
    NSMutableData *data;
    bool overflow;
} LinkSendPNGBuffer;

static NSPasteboard *linksendPasteboard(const char *name) {
    return name ? [NSPasteboard pasteboardWithName:[NSString stringWithUTF8String:name]] : NSPasteboard.generalPasteboard;
}

uint64_t linksendClipboardChangeCount(const char *name) {
    @autoreleasepool {
        @try {
            return (uint64_t)linksendPasteboard(name).changeCount;
        } @catch (NSException *exception) {
            (void)exception;
            return 0;
        }
    }
}

uint32_t linksendClipboardTypes(const char *name) {
    @autoreleasepool {
        @try {
            NSPasteboard *pasteboard = linksendPasteboard(name);
            NSArray<NSPasteboardType> *types = pasteboard.types;
            uint32_t result = 0;
            if ([types containsObject:NSPasteboardTypeString]) result |= 1;
            if ([types containsObject:NSPasteboardTypeURL]) result |= 2;
            if ([types containsObject:NSPasteboardTypePNG] || [types containsObject:NSPasteboardTypeTIFF]) result |= 4;
            return result;
        } @catch (NSException *exception) {
            (void)exception;
            return 0;
        }
    }
}

int linksendClipboardProhibited(const char *name) {
    @autoreleasepool { @try {
        NSArray<NSPasteboardType> *types = linksendPasteboard(name).types;
        NSArray<NSPasteboardType> *blocked = @[@"org.nspasteboard.TransientType", @"org.nspasteboard.ConcealedType", @"org.nspasteboard.AutoGeneratedType", @"com.agilebits.onepassword"];
        for (NSPasteboardType type in blocked) if ([types containsObject:type]) return 1;
        return 0;
    } @catch (NSException *exception) { (void)exception; return 1; } }
}

int linksendTestPasteboardString(const char *name, const char *value) {
    @autoreleasepool {
        @try {
            if (!name || !value) return 0;
            NSString *pasteboardName = [NSString stringWithUTF8String:name];
            if (![pasteboardName hasPrefix:@"com.linksend.native-test."]) return 0;
            NSPasteboard *pasteboard = [NSPasteboard pasteboardWithName:pasteboardName];
            [pasteboard clearContents];
            return [pasteboard setString:[NSString stringWithUTF8String:value] forType:NSPasteboardTypeString] ? 1 : 0;
        } @catch (NSException *exception) {
            (void)exception;
            return 0;
        }
    }
}

int linksendTestPasteboardMarker(const char *name, const char *marker) {
    @autoreleasepool {
        @try {
            if (!name || !marker) return 0;
            NSString *pasteboardName = [NSString stringWithUTF8String:name];
            if (![pasteboardName hasPrefix:@"com.linksend.native-test."]) return 0;
            NSPasteboard *pasteboard = [NSPasteboard pasteboardWithName:pasteboardName];
            [pasteboard clearContents];
            return [pasteboard setData:[NSData data] forType:[NSString stringWithUTF8String:marker]] ? 1 : 0;
        } @catch (NSException *exception) {
            (void)exception;
            return 0;
        }
    }
}

static size_t linksendPNGWrite(void *info, const void *buffer, size_t count) {
    LinkSendPNGBuffer *output = (LinkSendPNGBuffer *)info;
    if (count > LinkSendMaxImageBytes - output->data.length) {
        output->overflow = true;
        return 0;
    }
    [output->data appendBytes:buffer length:count];
    return count;
}

// Only losslessly snapshots pixels. No file URL dereference, HTML rendering,
// implicit URL launch, clipboard mutation or JavaScript bridge is involved.
int linksendClipboardPNG(const char *name, void **output, size_t *size) {
    *output = NULL;
    *size = 0;
    @autoreleasepool {
        @try {
            NSPasteboard *pasteboard = name ? [NSPasteboard pasteboardWithName:[NSString stringWithUTF8String:name]] : NSPasteboard.generalPasteboard;
            if (!pasteboard) return 4;
            NSInteger changeCount = pasteboard.changeCount;
            NSPasteboardType type = [pasteboard availableTypeFromArray:@[NSPasteboardTypePNG, NSPasteboardTypeTIFF]];
            if (!type) return 1;
            NSData *data = [pasteboard dataForType:type];
            if (pasteboard.changeCount != changeCount) return 3;
            if (!data) return 4;
            if (data.length == 0 || data.length > LinkSendMaxImageBytes) return 2;
            NSDictionary *options = @{(NSString *)kCGImageSourceShouldCache: @NO};
            CGImageSourceRef source = CGImageSourceCreateWithData((CFDataRef)data, (CFDictionaryRef)options);
            if (!source || CGImageSourceGetCount(source) != 1) { if (source) CFRelease(source); return 4; }
            CFDictionaryRef rawProperties = CGImageSourceCopyPropertiesAtIndex(source, 0, NULL);
            NSDictionary *properties = (NSDictionary *)rawProperties;
            uint64_t width = [properties[(NSString *)kCGImagePropertyPixelWidth] unsignedLongLongValue];
            uint64_t height = [properties[(NSString *)kCGImagePropertyPixelHeight] unsignedLongLongValue];
            if (rawProperties) CFRelease(rawProperties);
            if (width == 0 || height == 0 || width > LinkSendMaxImageDimension || height > LinkSendMaxImageDimension || width > LinkSendMaxImagePixels / height) { CFRelease(source); return 2; }
            CGImageRef image = CGImageSourceCreateImageAtIndex(source, 0, (CFDictionaryRef)options);
            CFRelease(source);
            if (!image) return 4;
            LinkSendPNGBuffer buffer = {[NSMutableData data], false};
            CGDataConsumerCallbacks callbacks = {linksendPNGWrite, NULL};
            CGDataConsumerRef consumer = CGDataConsumerCreate(&buffer, &callbacks);
            if (!consumer) { CGImageRelease(image); return 4; }
            CGImageDestinationRef destination = CGImageDestinationCreateWithDataConsumer(consumer, CFSTR("public.png"), 1, NULL);
            CGDataConsumerRelease(consumer);
            if (!destination) { CGImageRelease(image); return 4; }
            CGImageDestinationAddImage(destination, image, NULL);
            CGImageRelease(image);
            bool ok = CGImageDestinationFinalize(destination);
            CFRelease(destination);
            if (buffer.overflow) return 2;
            if (!ok || buffer.data.length == 0) return 4;
            if (pasteboard.changeCount != changeCount) return 3;
            *output = malloc(buffer.data.length);
            if (!*output) return 4;
            *size = buffer.data.length;
            memcpy(*output, buffer.data.bytes, *size);
            return 0;
        } @catch (NSException *exception) {
            (void)exception;
            return 4;
        }
    }
}

int linksendClipboardReadText(const char *name, int link, uint64_t expected, void **output, size_t *size, uint64_t *current) {
    *output = NULL; *size = 0;
    @autoreleasepool { @try {
        NSPasteboard *pasteboard = linksendPasteboard(name);
        *current = (uint64_t)pasteboard.changeCount;
        if (*current != expected) return 1;
        NSPasteboardType type = link ? NSPasteboardTypeURL : NSPasteboardTypeString;
        NSString *value = [pasteboard stringForType:type];
        if (!value && link) value = [pasteboard stringForType:NSPasteboardTypeString];
        NSData *data = [value dataUsingEncoding:NSUTF8StringEncoding];
        if (!data || data.length == 0 || data.length > 65536) return 2;
        if ((uint64_t)pasteboard.changeCount != expected) { *current = (uint64_t)pasteboard.changeCount; return 1; }
        *output = malloc(data.length); if (!*output) return 2;
        memcpy(*output, data.bytes, data.length); *size = data.length; return 0;
    } @catch (NSException *exception) { (void)exception; return 2; } }
}

int linksendClipboardWritePayload(const char *name, int kind, const void *data, size_t size, uint64_t expected, uint64_t *current) {
    @autoreleasepool { @try {
        NSPasteboard *pasteboard = linksendPasteboard(name);
        *current = (uint64_t)pasteboard.changeCount;
        if (*current != expected) return 1;
        if (!data || size == 0 || size > (32 * 1024 * 1024)) return 2;
        [pasteboard clearContents];
        BOOL ok = NO;
        if (kind == 2) {
            ok = [pasteboard setData:[NSData dataWithBytes:data length:size] forType:NSPasteboardTypePNG];
        } else {
            NSString *value = [[NSString alloc] initWithBytes:data length:size encoding:NSUTF8StringEncoding];
            if (!value) return 2;
            ok = [pasteboard setString:value forType:(kind == 1 ? NSPasteboardTypeURL : NSPasteboardTypeString)];
            if (kind == 1 && ok) [pasteboard setString:value forType:NSPasteboardTypeString];
            [value release];
        }
        *current = (uint64_t)pasteboard.changeCount;
        return ok ? 0 : 2;
    } @catch (NSException *exception) { (void)exception; return 2; } }
}
