// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the thin desktop boundary. Network and file services belong to internal/app.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../internal/app/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AcceptTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(1256230688, id);
}

export function AcceptTaskAlways(id: string): $CancellablePromise<void> {
    return $Call.ByID(805976429, id);
}

export function BlockPeer(id: string): $CancellablePromise<void> {
    return $Call.ByID(1661110154, id);
}

export function CancelQueue(id: string, revision: number): $CancellablePromise<void> {
    return $Call.ByID(3632256226, id, revision);
}

export function CancelTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(840985698, id);
}

export function ConfirmQueue(id: string, revision: number): $CancellablePromise<void> {
    return $Call.ByID(3080801262, id, revision);
}

export function CreateInvitation(): $CancellablePromise<app$0.InvitationInfo> {
    return $Call.ByID(997854590);
}

export function Devices(): $CancellablePromise<app$0.DeviceInfo[] | null> {
    return $Call.ByID(1642957352);
}

export function Diagnostics(): $CancellablePromise<app$0.Diagnostics> {
    return $Call.ByID(4058123183);
}

export function EffectiveConfig(): $CancellablePromise<$models.EffectiveConfig> {
    return $Call.ByID(329529236);
}

export function Enqueue(request: app$0.EnqueueRequest): $CancellablePromise<app$0.QueueItem> {
    return $Call.ByID(2200678053, request);
}

export function GetTask(id: string): $CancellablePromise<app$0.TaskSnapshot> {
    return $Call.ByID(3930404422, id);
}

export function Identity(): $CancellablePromise<app$0.IdentityInfo> {
    return $Call.ByID(1850161891);
}

export function InboxStatus(): $CancellablePromise<app$0.InboxStatus> {
    return $Call.ByID(602828805);
}

export function JoinGroup(token: string, name: string): $CancellablePromise<app$0.DeviceInfo> {
    return $Call.ByID(2730586904, token, name);
}

export function Membership(): $CancellablePromise<app$0.MembershipStatus> {
    return $Call.ByID(3247912641);
}

export function NetworkInterfaces(): $CancellablePromise<$models.NetworkInterfaceInfo[] | null> {
    return $Call.ByID(1900295361);
}

export function OpenTaskDirectory(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(3141333411, taskID);
}

/**
 * PairDevice is the user-facing alias for the simplified pairing-code flow.
 * JoinGroup remains for CLI/binding compatibility with existing clients.
 */
export function PairDevice(code: string, name: string): $CancellablePromise<app$0.DeviceInfo> {
    return $Call.ByID(2450051719, code, name);
}

export function PauseTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(3621607596, id);
}

export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1347829059);
}

export function PickFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(4162647679);
}

export function PickSourceDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1249895208);
}

export function Preferences(): $CancellablePromise<$models.DesktopPreferences> {
    return $Call.ByID(3579928677);
}

export function PreferencesStatus(): $CancellablePromise<$models.PreferencesStatus> {
    return $Call.ByID(2639668847);
}

export function ProbeLANAddress(address: string): $CancellablePromise<void> {
    return $Call.ByID(4182654780, address);
}

export function RefreshLANDiscovery(): $CancellablePromise<void> {
    return $Call.ByID(850507783);
}

export function RejectTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(3901406115, id);
}

export function ReorderQueue(ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1496578879, ids);
}

export function ResumeTask(id: string): $CancellablePromise<app$0.TaskSnapshot> {
    return $Call.ByID(1059512591, id);
}

export function RetryTask(id: string): $CancellablePromise<app$0.TaskSnapshot> {
    return $Call.ByID(3354333520, id);
}

export function SaveDeviceProfile(profile: app$0.DeviceProfile): $CancellablePromise<app$0.DeviceProfile> {
    return $Call.ByID(3209168119, profile);
}

export function SaveDraft(draft: app$0.SendDraft): $CancellablePromise<app$0.SendDraft> {
    return $Call.ByID(3025273299, draft);
}

export function SavePreferences(next: $models.DesktopPreferences): $CancellablePromise<void> {
    return $Call.ByID(3232231562, next);
}

export function SetAlwaysAccept(deviceID: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3711226762, deviceID, enabled);
}

export function SetQueuePaused(paused: boolean): $CancellablePromise<void> {
    return $Call.ByID(102829032, paused);
}

export function StartReceive(expectedPeerID: string, directory: string): $CancellablePromise<app$0.TaskSnapshot> {
    return $Call.ByID(3272686060, expectedPeerID, directory);
}

export function StartSend(peerID: string, paths: string[] | null): $CancellablePromise<app$0.TaskSnapshot> {
    return $Call.ByID(1052991585, peerID, paths);
}

/**
 * Status reports this running shell only; it does not claim a P2P connection.
 */
export function Status(): $CancellablePromise<$models.DesktopStatus> {
    return $Call.ByID(2836613335);
}

export function Tasks(): $CancellablePromise<app$0.TaskSnapshot[] | null> {
    return $Call.ByID(151226709);
}

export function TrustDevice(deviceID: string, fingerprint: string): $CancellablePromise<void> {
    return $Call.ByID(4070375595, deviceID, fingerprint);
}

export function UnblockPeer(id: string): $CancellablePromise<void> {
    return $Call.ByID(493225303, id);
}

export function Workspace(): $CancellablePromise<app$0.WorkspaceSnapshot> {
    return $Call.ByID(4123709102);
}
