// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the thin desktop boundary. Network and file services belong to internal/app.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../internal/app/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AcceptTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(1256230688, id);
}

export function CancelTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(840985698, id);
}

export function CreateInvitation(): $CancellablePromise<app$0.InvitationInfo> {
    return $Call.ByID(997854590);
}

export function Devices(): $CancellablePromise<app$0.DeviceInfo[] | null> {
    return $Call.ByID(1642957352);
}

export function Diagnostics(): $CancellablePromise<app$0.Diagnostics> {
    return $Call.ByID(4058123183);
}

export function EffectiveConfig(): $CancellablePromise<$models.EffectiveConfig> {
    return $Call.ByID(329529236);
}

export function GetTask(id: string): $CancellablePromise<app$0.TaskSnapshot> {
    return $Call.ByID(3930404422, id);
}

export function Identity(): $CancellablePromise<app$0.IdentityInfo> {
    return $Call.ByID(1850161891);
}

export function JoinGroup(token: string, name: string): $CancellablePromise<app$0.DeviceInfo> {
    return $Call.ByID(2730586904, token, name);
}

export function Membership(): $CancellablePromise<app$0.MembershipStatus> {
    return $Call.ByID(3247912641);
}

export function NetworkInterfaces(): $CancellablePromise<$models.NetworkInterfaceInfo[] | null> {
    return $Call.ByID(1900295361);
}

export function OpenTaskDirectory(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(3141333411, taskID);
}

export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1347829059);
}

export function PickFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(4162647679);
}

export function PickSourceDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1249895208);
}

export function Preferences(): $CancellablePromise<$models.DesktopPreferences> {
    return $Call.ByID(3579928677);
}

export function PreferencesStatus(): $CancellablePromise<$models.PreferencesStatus> {
    return $Call.ByID(2639668847);
}

export function RejectTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(3901406115, id);
}

export function RetryTask(id: string): $CancellablePromise<app$0.TaskSnapshot> {
    return $Call.ByID(3354333520, id);
}

export function SavePreferences(next: $models.DesktopPreferences): $CancellablePromise<void> {
    return $Call.ByID(3232231562, next);
}

export function StartReceive(expectedPeerID: string, directory: string): $CancellablePromise<app$0.TaskSnapshot> {
    return $Call.ByID(3272686060, expectedPeerID, directory);
}

export function StartSend(peerID: string, paths: string[] | null): $CancellablePromise<app$0.TaskSnapshot> {
    return $Call.ByID(1052991585, peerID, paths);
}

/**
 * Status reports this running shell only; it does not claim a P2P connection.
 */
export function Status(): $CancellablePromise<$models.DesktopStatus> {
    return $Call.ByID(2836613335);
}

export function Tasks(): $CancellablePromise<app$0.TaskSnapshot[] | null> {
    return $Call.ByID(151226709);
}

export function TrustDevice(deviceID: string, fingerprint: string): $CancellablePromise<void> {
    return $Call.ByID(4070375595, deviceID, fingerprint);
}
