// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as App from "./app.js";
export {
    App
};

export type {
    BackgroundOptions,
    BackgroundStatus,
    DesktopEntryStatus,
    DesktopPreferences,
    DesktopStatus,
    EffectiveConfig,
    NetworkInterfaceInfo,
    PreferencesStatus
} from "./models.js";
