// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nativeclipboard$0 from "./nativeclipboard/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../internal/app/models.js";

export interface BackgroundOptions {
    /**
     * empty = ask once, exit, background
     */
    "close_mode": string;
    "notifications": boolean;
    "prevent_sleep": boolean;
}

export interface BackgroundStatus {
    "options": BackgroundOptions;
    "tray_available": boolean;
    "sleep_inhibited": boolean;
    "notification_permission": string;
    "last_notification": string;
    "error"?: string;
    "navigation_revision": number;
    "task_id"?: string;
    "autostart": boolean;
}

export interface ClipboardWatchStatus {
    "enabled": boolean;
    "master_enabled": boolean;
    "active": boolean;
    "paused": boolean;
    "pause_reason"?: string;
    "last": nativeclipboard$0.Change;
    "error"?: string;
    "peers": app$0.ClipboardPeerStatus[] | null;
}

export interface DesktopEntryStatus {
    "revision": number;
    "error"?: string;
    "draft_revision": number;
    "send_to_supported": boolean;
    "finder_services": boolean;
    "pending_shares"?: NativeSharePending[] | null;
}

export interface DesktopPreferences {
    "format_version": number;
    "revision": number;
    "server_url": string;
    "bind_address": string;
    "interface_priority": string[] | null;
    "excluded_interfaces": string[] | null;
    "stun_urls": string[] | null;
    "receive_directory": string;
    "conflict_policy": string;
    "device_name": string;
    "background": BackgroundOptions;
    "clipboard_enabled": boolean;
}

export interface DesktopStatus {
    "version": string;
    "platform": string;
    "relay": boolean;
    "stage": string;
    "ready": boolean;
    "error"?: string;
    "identity"?: string;
}

export interface EffectiveConfig {
    "server_url": string;
    "server_source": string;
    "bind_address": string;
    "bind_source": string;
    "interface_priority": string[] | null;
    "excluded_interfaces": string[] | null;
    "stun_urls": string[] | null;
    "stun_source": string;
    "needs_restart": boolean;
    "preferences_state": string;
}

export interface NativeSharePending {
    "request_id": string;
    "peer_id": string;
}

export interface NetworkInterfaceInfo {
    "name": string;
    "addresses": string[] | null;
    "address_families": string[] | null;
    "is_loopback": boolean;
}

export interface PreferencesStatus {
    "state": string;
    "message"?: string;
}
