// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DesktopEntryStatus {
    "revision": number;
    "error"?: string;
    "draft_revision": number;
    "send_to_supported": boolean;
    "finder_services": boolean;
}

export interface DesktopPreferences {
    "format_version": number;
    "server_url": string;
    "bind_address": string;
    "interface_priority": string[] | null;
    "excluded_interfaces": string[] | null;
    "stun_urls": string[] | null;
    "receive_directory": string;
    "device_name": string;
}

export interface DesktopStatus {
    "version": string;
    "platform": string;
    "relay": boolean;
    "stage": string;
    "ready": boolean;
    "error"?: string;
    "identity"?: string;
}

export interface EffectiveConfig {
    "server_url": string;
    "server_source": string;
    "bind_address": string;
    "bind_source": string;
    "interface_priority": string[] | null;
    "excluded_interfaces": string[] | null;
    "stun_urls": string[] | null;
    "stun_source": string;
    "needs_restart": boolean;
    "preferences_state": string;
}

export interface NetworkInterfaceInfo {
    "name": string;
    "addresses": string[] | null;
    "address_families": string[] | null;
    "is_loopback": boolean;
}

export interface PreferencesStatus {
    "state": string;
    "message"?: string;
}
