// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as content$0 from "../content/models.js";

export enum ConflictPolicy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ConflictError = "error",
    ConflictKeepBoth = "keep_both",
    ConflictSkip = "skip",
};

/**
 * ContentDescriptor contains metadata only. Digest is the lowercase BLAKE3-256
 * of the file body, matching content.Snapshot.Digest and FileEntry.Hash.
 * It is deliberately separate from Manifest, whose legacy JSON stays unchanged.
 * URL is a sender-provided type hint, never permission to open it. Received
 * values must pass content.ValidateURL again at the explicit open action;
 * unsupported schemes are displayed as inert text.
 */
export interface ContentDescriptor {
    "version": number;
    "entry_id": number;
    "kind": content$0.Kind;
    "media_type": string;
    "size": number;
    "digest": string;
    "width"?: number;
    "height"?: number;
}

export interface PlanSummary {
    "original_total": number;
    "selected_total": number;
    "selected_files": number;
    "selected_entries": number;
    "skipped_files": number;
    "skipped_entries": number;
    "skipped_bytes": number;
    "remaining_bytes": number;
    "commit_bytes": number;
}
