// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum ConflictPolicy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ConflictError = "error",
    ConflictKeepBoth = "keep_both",
    ConflictSkip = "skip",
};

export interface PlanSummary {
    "original_total": number;
    "selected_total": number;
    "selected_files": number;
    "selected_entries": number;
    "skipped_files": number;
    "skipped_entries": number;
    "skipped_bytes": number;
    "remaining_bytes": number;
    "commit_bytes": number;
}
