[CmdletBinding()]
param([ValidateSet('preflight','receiver','sender')][string]$Role='preflight',[string]$Server=$env:LINKSEND_SERVER,[string]$Stun=$env:LINKSEND_STUN,[string]$Bind=$env:LINKSEND_BIND,[string]$DataDir=$env:LINKSEND_DATA_DIR,[string]$ReceiveDir=$env:LINKSEND_RECEIVE_DIR,[string]$Peer=$env:LINKSEND_PEER,[string[]]$File,[switch]$SkipBuild)
$ErrorActionPreference='Stop'; if(!$Server){throw '请提供 -Server'}; if(!$DataDir){$DataDir='.stage2a/profile'}; $root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path; $evidence=Join-Path $root ('.stage2a\'+(Get-Date -Format yyyyMMdd-HHmmss)); New-Item -ItemType Directory -Force $evidence,(Join-Path $root $DataDir) | Out-Null
function Run($n,[scriptblock]$b){&$b *>&1|Tee-Object (Join-Path $evidence "$n.log");if($LASTEXITCODE){throw "$n 失败"}}
if(!(Get-Command go -EA SilentlyContinue)){throw '未找到 Go 1.26.5'}; Run go-version {go version}; $u=[Uri]$Server; if($u.Host -match '^(localhost|127\.|::1)$'){throw '2A 禁止 loopback 信令地址'}; Run dns {Resolve-DnsName $u.Host -Type A_AAAA -EA Stop}; if(!$SkipBuild){Run build {go build -trimpath -o (Join-Path $evidence 'linksend.exe') ./cmd/linksend}}
[ordered]@{role=$Role;server=$Server;stun=$Stun;bind=$Bind;started=(Get-Date).ToString('o');host=$env:COMPUTERNAME}|ConvertTo-Json|Set-Content (Join-Path $evidence run.json) -Encoding utf8
if($Role -eq 'preflight'){Write-Host "2A 预检完成: $evidence";exit 0}; if(!$Bind){throw '真实 2A 必须提供 -Bind'}; $bin=if($SkipBuild){'go'}else{Join-Path $evidence 'linksend.exe'}; $common=@('--server',$Server,'--data-dir',(Resolve-Path $DataDir).Path)
if($Role -eq 'receiver'){if(!$ReceiveDir){throw 'receiver 必须提供 -ReceiveDir'};&$bin @common receive --dir $ReceiveDir --bind $Bind --stun $Stun --evidence --auto-accept 2>&1|Tee-Object (Join-Path $evidence transfer.log)}else{if(!$Peer -or !$File){throw 'sender 必须提供 -Peer 和 -File'};&$bin @common send --peer $Peer --bind $Bind --stun $Stun --evidence @File 2>&1|Tee-Object (Join-Path $evidence transfer.log)};if($LASTEXITCODE){throw '传输失败'};Write-Host "2A $Role 完成: $evidence"

