// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Capabilities {
    "protocol_version": number;
    "relay": boolean;
    "transport": string;
    "history_persisted": boolean;
    "restart_recovery_supported": boolean;
    "byte_resume_supported": boolean;
}
