// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Text = "text",
    URL = "url",
    Image = "image",
};

/**
 * Snapshot deliberately excludes local paths, text previews and encoded bytes.
 */
export interface Snapshot {
    "id": string;
    "kind": Kind;
    "size": number;
    "digest": string;
    "media_type": string;
    "width"?: number;
    "height"?: number;
    "created_at": string;
}
